### ISSUE TITLE
Nice Terri Bot script

### ISSUE THREAD

**Issue by Teinc3** [mohsenemx/FXclient#1]
Mind sharing the source with me (I am definitely not main server admin)

(For those who don't know he is not the real botter lol)

**Comment by mohsenemx** [comment]
You are dumb enough that don't know our project is completely open source and it's deployed on same source on github pages. Try to do some research next time kid. Source code is already there infront of your eyes.

**Comment by theotherhades** [comment]
LMAOOO

**Comment by theotherhades** [comment]
You just gon sit there and take it @Teinc3?

**Comment by Teinc3** [comment]
I mean, if you actually read the conversation you'd have known who clowned themselves the most, but for the sake of clarity, I am still making you a reply here
